// <auto-generated />
using System;
using Cleriq.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cleriq.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260630114723_AddMotivInvalidareAltulText")]
    partial class AddMotivInvalidareAltulText
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Cleriq.Models.Comisie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatDe")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatLa")
                        .HasColumnType("datetime2");

                    b.Property<string>("Denumire")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Descriere")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("EsteSters")
                        .HasColumnType("bit");

                    b.Property<int>("InstitutieId")
                        .HasColumnType("int");

                    b.Property<int?>("ModificatDe")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModificatLa")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int?>("StersDe")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StersLa")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("InstitutieId");

                    b.ToTable("Comisii");
                });

            modelBuilder.Entity("Cleriq.Models.ComisieMembru", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ComisieId")
                        .HasColumnType("int");

                    b.Property<int>("ConsilierId")
                        .HasColumnType("int");

                    b.Property<int?>("CreatDe")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatLa")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("DataInceput")
                        .HasColumnType("date");

                    b.Property<bool>("DataInceputEstimata")
                        .HasColumnType("bit");

                    b.Property<DateOnly?>("DataSfarsit")
                        .HasColumnType("date");

                    b.Property<bool>("EsteSters")
                        .HasColumnType("bit");

                    b.Property<int>("InstitutieId")
                        .HasColumnType("int");

                    b.Property<int?>("ModificatDe")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModificatLa")
                        .HasColumnType("datetime2");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int?>("StersDe")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StersLa")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ConsilierId");

                    b.HasIndex("InstitutieId");

                    b.HasIndex("ComisieId", "ConsilierId")
                        .IsUnique()
                        .HasFilter("[EsteSters] = 0 AND [DataSfarsit] IS NULL");

                    b.ToTable("ComisieMembri");
                });

            modelBuilder.Entity("Cleriq.Models.ComunicareHclPrefect", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnRegistru")
                        .HasColumnType("int");

                    b.Property<int>("CanalTransmitere")
                        .HasColumnType("int");

                    b.Property<int?>("CreatDe")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatLa")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly?>("DataConfirmarePrefect")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DataInregistrareInRegistru")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DataRaspunsPrefect")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DataTrimiteri")
                        .HasColumnType("date");

                    b.Property<bool>("EsteSters")
                        .HasColumnType("bit");

                    b.Property<int>("HclId")
                        .HasColumnType("int");

                    b.Property<int>("InstitutieId")
                        .HasColumnType("int");

                    b.Property<int?>("ModificatDe")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModificatLa")
                        .HasColumnType("datetime2");

                    b.Property<string>("NrInregistrarePrefect")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("NumarOrdineInRegistru")
                        .HasColumnType("int");

                    b.Property<string>("ObiectiiMotivate")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("ObservatiiInterne")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RaspunsPrefect")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int?>("StersDe")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StersLa")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("HclId");

                    b.HasIndex("InstitutieId", "AnRegistru", "NumarOrdineInRegistru")
                        .IsUnique()
                        .HasFilter("[EsteSters] = 0");

                    b.ToTable("ComunicariHclPrefect");
                });

            modelBuilder.Entity("Cleriq.Models.Consilier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activ")
                        .HasColumnType("bit");

                    b.Property<int?>("CreatDe")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatLa")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EsteSters")
                        .HasColumnType("bit");

                    b.Property<int>("InstitutieId")
                        .HasColumnType("int");

                    b.Property<int?>("ModificatDe")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModificatLa")
                        .HasColumnType("datetime2");

                    b.Property<string>("NumeComplet")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int?>("StersDe")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StersLa")
                        .HasColumnType("datetime2");

                    b.Property<string>("Telefon")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("InstitutieId");

                    b.ToTable("Consilieri");
                });

            modelBuilder.Entity("Cleriq.Models.Convocare", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ConsilierId")
                        .HasColumnType("int");

                    b.Property<int?>("CreatDe")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatLa")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailDetalii")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("EmailHtml")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EmailStatus")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EmailTrimisLa")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EsteSters")
                        .HasColumnType("bit");

                    b.Property<int>("InstitutieId")
                        .HasColumnType("int");

                    b.Property<int?>("ModificatDe")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModificatLa")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("SedintaId")
                        .HasColumnType("int");

                    b.Property<string>("SmsDetalii")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("SmsStatus")
                        .HasColumnType("int");

                    b.Property<string>("SmsText")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("SmsTrimisLa")
                        .HasColumnType("datetime2");

                    b.Property<int?>("StersDe")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StersLa")
                        .HasColumnType("datetime2");

                    b.Property<string>("Subiect")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ConsilierId");

                    b.HasIndex("InstitutieId");

                    b.HasIndex("SedintaId", "ConsilierId")
                        .IsUnique()
                        .HasFilter("[EsteSters] = 0");

                    b.ToTable("Convocari");
                });

            modelBuilder.Entity("Cleriq.Models.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CaleStocare")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("CreatDe")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatLa")
                        .HasColumnType("datetime2");

                    b.Property<string>("Denumire")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Descriere")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("EstePublic")
                        .HasColumnType("bit");

                    b.Property<bool>("EsteSters")
                        .HasColumnType("bit");

                    b.Property<string>("HashSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int?>("HclId")
                        .HasColumnType("int");

                    b.Property<int>("InstitutieId")
                        .HasColumnType("int");

                    b.Property<long>("Marime")
                        .HasColumnType("bigint");

                    b.Property<int?>("ModificatDe")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModificatLa")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NumarOrdinAnexa")
                        .HasColumnType("int");

                    b.Property<string>("NumeFisierOriginal")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Ordine")
                        .HasColumnType("int");

                    b.Property<int?>("PunctId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int?>("SedintaId")
                        .HasColumnType("int");

                    b.Property<int?>("StersDe")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StersLa")
                        .HasColumnType("datetime2");

                    b.Property<int>("TipDocument")
                        .HasColumnType("int");

                    b.Property<int?>("TipDocumentHcl")
                        .HasColumnType("int");

                    b.Property<string>("TipMime")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("InstitutieId");

                    b.HasIndex("PunctId");

                    b.HasIndex("SedintaId");

                    b.HasIndex("HclId", "NumarOrdinAnexa")
                        .IsUnique()
                        .HasFilter("[EsteSters] = 0 AND [TipDocumentHcl] = 1 AND [HclId] IS NOT NULL");

                    b.ToTable("Documente", t =>
                        {
                            t.HasCheckConstraint("CK_Document_AnexaMetadata", "[TipDocumentHcl] IS NULL OR [TipDocumentHcl] != 1 OR [NumarOrdinAnexa] IS NOT NULL");

                            t.HasCheckConstraint("CK_Document_ExactUnContext", "(CASE WHEN [SedintaId] IS NULL THEN 0 ELSE 1 END +  CASE WHEN [PunctId] IS NULL THEN 0 ELSE 1 END +  CASE WHEN [HclId] IS NULL THEN 0 ELSE 1 END) = 1");
                        });
                });

            modelBuilder.Entity("Cleriq.Models.Hcl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AnNumerotare")
                        .HasColumnType("int");

                    b.Property<string>("CaleStocareSemnat")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Continut")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreatDe")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatLa")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataAdoptare")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataIncarcareSemnat")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly?>("DataIntrareInVigoare")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DataInvalidare")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataPublicareMol")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EstePublicat")
                        .HasColumnType("bit");

                    b.Property<bool>("EsteSters")
                        .HasColumnType("bit");

                    b.Property<string>("HashSha256Semnat")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("InstitutieId")
                        .HasColumnType("int");

                    b.Property<int?>("InvalidatDe")
                        .HasColumnType("int");

                    b.Property<long?>("MarimeSemnat")
                        .HasColumnType("bigint");

                    b.Property<int?>("ModificatDe")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModificatLa")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MotivInvalidare")
                        .HasColumnType("int");

                    b.Property<string>("MotivInvalidareAltulText")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("MotivLipsaSemnaturaPresedinte")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("Numar")
                        .HasColumnType("int");

                    b.Property<string>("NumeFisierSemnat")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("PublicataDe")
                        .HasColumnType("int");

                    b.Property<int>("PunctOrdineZiId")
                        .HasColumnType("int");

                    b.Property<string>("RefInvalidare")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("StersDe")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StersLa")
                        .HasColumnType("datetime2");

                    b.Property<int>("TipHcl")
                        .HasColumnType("int");

                    b.Property<int>("TipMajoritate")
                        .HasColumnType("int");

                    b.Property<string>("Titlu")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("VotAbtinere")
                        .HasColumnType("int");

                    b.Property<int>("VotImpotriva")
                        .HasColumnType("int");

                    b.Property<int>("VotPentru")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PunctOrdineZiId")
                        .IsUnique()
                        .HasFilter("[EsteSters] = 0");

                    b.HasIndex("InstitutieId", "AnNumerotare", "Numar")
                        .IsUnique()
                        .HasFilter("[EsteSters] = 0 AND [Numar] IS NOT NULL");

                    b.ToTable("Hcluri");
                });

            modelBuilder.Entity("Cleriq.Models.IncercareTrimitere", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Canal")
                        .HasColumnType("int");

                    b.Property<int>("ConvocareId")
                        .HasColumnType("int");

                    b.Property<int?>("CreatDe")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatLa")
                        .HasColumnType("datetime2");

                    b.Property<string>("Destinatar")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Detalii")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("EsteSters")
                        .HasColumnType("bit");

                    b.Property<int>("InstitutieId")
                        .HasColumnType("int");

                    b.Property<int?>("ModificatDe")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModificatLa")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("StersDe")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StersLa")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("InstitutieId");

                    b.HasIndex("ConvocareId", "Canal", "CreatLa");

                    b.ToTable("IncercariTrimitere");
                });

            modelBuilder.Entity("Cleriq.Models.Institutie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodSiruta")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("CreatDe")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatLa")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataExpirare")
                        .HasColumnType("datetime2");

                    b.Property<string>("Denumire")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("EsteSters")
                        .HasColumnType("bit");

                    b.Property<string>("FusOrar")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("Europe/Bucharest");

                    b.Property<string>("Judet")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ModificatDe")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModificatLa")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SmtpEmailFrom")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("SmtpHost")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SmtpNumeFrom")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SmtpParolaCriptata")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int?>("SmtpPort")
                        .HasColumnType("int");

                    b.Property<int>("SmtpSecuritate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("SmtpUtilizator")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("StatusAbonament")
                        .HasColumnType("int");

                    b.Property<int?>("StersDe")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StersLa")
                        .HasColumnType("datetime2");

                    b.Property<int>("Tip")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Institutii");
                });

            modelBuilder.Entity("Cleriq.Models.Mandat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ConsilierId")
                        .HasColumnType("int");

                    b.Property<int?>("CreatDe")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatLa")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("DataInceput")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DataSfarsit")
                        .HasColumnType("date");

                    b.Property<bool>("EsteSters")
                        .HasColumnType("bit");

                    b.Property<string>("GrupPolitic")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("InstitutieId")
                        .HasColumnType("int");

                    b.Property<int?>("ModificatDe")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModificatLa")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int?>("StersDe")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StersLa")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ConsilierId");

                    b.HasIndex("InstitutieId");

                    b.ToTable("Mandate");
                });

            modelBuilder.Entity("Cleriq.Models.MandatFunctie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ConsilierId")
                        .HasColumnType("int");

                    b.Property<int?>("CreatDe")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatLa")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("DataInceput")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DataSfarsit")
                        .HasColumnType("date");

                    b.Property<bool>("EsteSters")
                        .HasColumnType("bit");

                    b.Property<int>("InstitutieId")
                        .HasColumnType("int");

                    b.Property<int?>("ModificatDe")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModificatLa")
                        .HasColumnType("datetime2");

                    b.Property<string>("NrActNumire")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("PersoanaId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int?>("StersDe")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StersLa")
                        .HasColumnType("datetime2");

                    b.Property<int>("TipFunctie")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConsilierId");

                    b.HasIndex("PersoanaId");

                    b.HasIndex(new[] { "InstitutieId" }, "IX_MandatFunctie_PrimarActiv")
                        .IsUnique()
                        .HasFilter("[EsteSters] = 0 AND [DataSfarsit] IS NULL AND [TipFunctie] = 1");

                    b.HasIndex(new[] { "InstitutieId" }, "IX_MandatFunctie_SecretarUatActiv")
                        .IsUnique()
                        .HasFilter("[EsteSters] = 0 AND [DataSfarsit] IS NULL AND [TipFunctie] = 3");

                    b.HasIndex(new[] { "InstitutieId", "ConsilierId" }, "IX_MandatFunctie_ViceprimarActivPerConsilier")
                        .IsUnique()
                        .HasFilter("[EsteSters] = 0 AND [DataSfarsit] IS NULL AND [TipFunctie] = 2");

                    b.ToTable("MandateFunctie", t =>
                        {
                            t.HasCheckConstraint("CK_MandatFunctie_ExactUnSubject", "(CASE WHEN [PersoanaId] IS NULL THEN 0 ELSE 1 END +  CASE WHEN [ConsilierId] IS NULL THEN 0 ELSE 1 END) = 1");

                            t.HasCheckConstraint("CK_MandatFunctie_FkCorectaPerTip", "([TipFunctie] IN (1, 3) AND [PersoanaId] IS NOT NULL AND [ConsilierId] IS NULL) OR ([TipFunctie] = 2 AND [ConsilierId] IS NOT NULL AND [PersoanaId] IS NULL)");

                            t.HasCheckConstraint("CK_MandatFunctie_PerioadaValida", "[DataSfarsit] IS NULL OR [DataSfarsit] >= [DataInceput]");
                        });
                });

            modelBuilder.Entity("Cleriq.Models.Persoana", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatDe")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatLa")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EsteSters")
                        .HasColumnType("bit");

                    b.Property<int>("InstitutieId")
                        .HasColumnType("int");

                    b.Property<int?>("ModificatDe")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModificatLa")
                        .HasColumnType("datetime2");

                    b.Property<string>("NumeComplet")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int?>("StersDe")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StersLa")
                        .HasColumnType("datetime2");

                    b.Property<string>("Telefon")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("InstitutieId", "NumeComplet");

                    b.ToTable("Persoane");
                });

            modelBuilder.Entity("Cleriq.Models.Prezenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ConsilierId")
                        .HasColumnType("int");

                    b.Property<int?>("CreatDe")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatLa")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EsteSters")
                        .HasColumnType("bit");

                    b.Property<int>("InstitutieId")
                        .HasColumnType("int");

                    b.Property<int?>("ModificatDe")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModificatLa")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("OraSosire")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("SedintaId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("StersDe")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StersLa")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ConsilierId");

                    b.HasIndex("InstitutieId");

                    b.HasIndex("SedintaId", "ConsilierId")
                        .IsUnique()
                        .HasFilter("[EsteSters] = 0");

                    b.ToTable("Prezente");
                });

            modelBuilder.Entity("Cleriq.Models.ProcesVerbal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AprobatDe")
                        .HasColumnType("int");

                    b.Property<int?>("AprobatInSedintaId")
                        .HasColumnType("int");

                    b.Property<string>("CaleStocareSemnat")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Continut")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreatDe")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatLa")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataAprobare")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataFinalizare")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataGenerare")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataIncarcareSemnat")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EsteSters")
                        .HasColumnType("bit");

                    b.Property<string>("HashSha256Semnat")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("InstitutieId")
                        .HasColumnType("int");

                    b.Property<long?>("MarimeSemnat")
                        .HasColumnType("bigint");

                    b.Property<int?>("ModificatDe")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModificatLa")
                        .HasColumnType("datetime2");

                    b.Property<string>("NumeFisierSemnat")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("SedintaId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("StersDe")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StersLa")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AprobatInSedintaId");

                    b.HasIndex("InstitutieId");

                    b.HasIndex("SedintaId")
                        .IsUnique();

                    b.ToTable("ProceseVerbale");
                });

            modelBuilder.Entity("Cleriq.Models.PunctOrdineZi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatDe")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatLa")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descriere")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EsteSters")
                        .HasColumnType("bit");

                    b.Property<int>("InstitutieId")
                        .HasColumnType("int");

                    b.Property<int?>("ModificatDe")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModificatLa")
                        .HasColumnType("datetime2");

                    b.Property<bool>("NecesitaVot")
                        .HasColumnType("bit");

                    b.Property<int>("Ordine")
                        .HasColumnType("int");

                    b.Property<int?>("Rezultat")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("SedintaId")
                        .HasColumnType("int");

                    b.Property<int?>("StersDe")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StersLa")
                        .HasColumnType("datetime2");

                    b.Property<int>("Tip")
                        .HasColumnType("int");

                    b.Property<int?>("TipMajoritate")
                        .HasColumnType("int");

                    b.Property<int>("TipVot")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("Titlu")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("InstitutieId");

                    b.HasIndex("SedintaId");

                    b.ToTable("PuncteOrdineZi");
                });

            modelBuilder.Entity("Cleriq.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatLa")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiraLa")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Familie")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("FolositLa")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RevocatLa")
                        .HasColumnType("datetime2");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("UtilizatorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Familie");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UtilizatorId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Cleriq.Models.RelatieHcl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatDe")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatLa")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EsteSters")
                        .HasColumnType("bit");

                    b.Property<int>("HclSursaId")
                        .HasColumnType("int");

                    b.Property<int?>("HclTintaId")
                        .HasColumnType("int");

                    b.Property<int>("InstitutieId")
                        .HasColumnType("int");

                    b.Property<int?>("ModificatDe")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModificatLa")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReferintaActExternText")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int?>("StersDe")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StersLa")
                        .HasColumnType("datetime2");

                    b.Property<int>("TipRelatie")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HclTintaId");

                    b.HasIndex("InstitutieId");

                    b.HasIndex("HclSursaId", "HclTintaId", "TipRelatie")
                        .IsUnique()
                        .HasFilter("[EsteSters] = 0 AND [HclTintaId] IS NOT NULL");

                    b.ToTable("RelatiiHcl", t =>
                        {
                            t.HasCheckConstraint("CK_RelatieHcl_ExactUnaTinta", "(CASE WHEN [HclTintaId] IS NULL THEN 0 ELSE 1 END +  CASE WHEN [ReferintaActExternText] IS NULL THEN 0 ELSE 1 END) = 1");
                        });
                });

            modelBuilder.Entity("Cleriq.Models.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Cleriq.Models.Sedinta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ConvocareTrimisaLa")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatDe")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatLa")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataOra")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EsteSters")
                        .HasColumnType("bit");

                    b.Property<int>("InstitutieId")
                        .HasColumnType("int");

                    b.Property<string>("Loc")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("ModDesfasurare")
                        .HasColumnType("int");

                    b.Property<int?>("ModificatDe")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModificatLa")
                        .HasColumnType("datetime2");

                    b.Property<string>("Numar")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("PresedinteSedintaConsilierId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("StersDe")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StersLa")
                        .HasColumnType("datetime2");

                    b.Property<int>("Tip")
                        .HasColumnType("int");

                    b.Property<string>("Titlu")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("InstitutieId");

                    b.HasIndex("PresedinteSedintaConsilierId");

                    b.ToTable("Sedinte");
                });

            modelBuilder.Entity("Cleriq.Models.SemnatarHcl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ConsilierId")
                        .HasColumnType("int");

                    b.Property<int?>("CreatDe")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatLa")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("DataSemnare")
                        .HasColumnType("date");

                    b.Property<bool>("EsteSters")
                        .HasColumnType("bit");

                    b.Property<int>("HclId")
                        .HasColumnType("int");

                    b.Property<int>("InstitutieId")
                        .HasColumnType("int");

                    b.Property<int?>("ModificatDe")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModificatLa")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrdineAfisare")
                        .HasColumnType("int");

                    b.Property<int?>("PersoanaId")
                        .HasColumnType("int");

                    b.Property<int>("RolSemnatar")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int?>("StersDe")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StersLa")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ConsilierId");

                    b.HasIndex("InstitutieId");

                    b.HasIndex("PersoanaId");

                    b.HasIndex(new[] { "HclId" }, "IX_SemnatarHcl_PresedinteSedintaActiv")
                        .IsUnique()
                        .HasFilter("[EsteSters] = 0 AND [RolSemnatar] = 1");

                    b.HasIndex(new[] { "HclId" }, "IX_SemnatarHcl_SecretarUatActiv")
                        .IsUnique()
                        .HasFilter("[EsteSters] = 0 AND [RolSemnatar] = 2");

                    b.ToTable("SemnatariHcl", t =>
                        {
                            t.HasCheckConstraint("CK_SemnatarHcl_ExactUnSubject", "(CASE WHEN [PersoanaId] IS NULL THEN 0 ELSE 1 END +  CASE WHEN [ConsilierId] IS NULL THEN 0 ELSE 1 END) = 1");

                            t.HasCheckConstraint("CK_SemnatarHcl_FkCorectaPerRol", "([RolSemnatar] = 2 AND [PersoanaId] IS NOT NULL AND [ConsilierId] IS NULL) OR ([RolSemnatar] IN (1, 3) AND [ConsilierId] IS NOT NULL AND [PersoanaId] IS NULL)");
                        });
                });

            modelBuilder.Entity("Cleriq.Models.Transcriere", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CaleStocareAudio")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ContinutBrut")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContinutEditat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContinutPublicat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreatDe")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatLa")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataPrimireBrut")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataPublicare")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataUltimeiEditari")
                        .HasColumnType("datetime2");

                    b.Property<long>("DimensiuneAudio")
                        .HasColumnType("bigint");

                    b.Property<int?>("DurataAudioSecunde")
                        .HasColumnType("int");

                    b.Property<bool>("EsteSters")
                        .HasColumnType("bit");

                    b.Property<int>("InstitutieId")
                        .HasColumnType("int");

                    b.Property<string>("ModelFolosit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ModificatDe")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModificatLa")
                        .HasColumnType("datetime2");

                    b.Property<int>("NumarEsecuri")
                        .HasColumnType("int");

                    b.Property<string>("PromptFolosit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PublicataDe")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("SedintaId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("StersDe")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StersLa")
                        .HasColumnType("datetime2");

                    b.Property<string>("UltimaEroare")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("UrmatoareaIncercareDupa")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("InstitutieId");

                    b.HasIndex("SedintaId")
                        .IsUnique()
                        .HasFilter("[EsteSters] = 0");

                    b.ToTable("Transcrieri");
                });

            modelBuilder.Entity("Cleriq.Models.Utilizator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ConsilierId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("InstitutieId")
                        .HasColumnType("int");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NumeComplet")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("ConsilierId")
                        .IsUnique()
                        .HasFilter("[ConsilierId] IS NOT NULL");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Cleriq.Models.Vot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ConsilierId")
                        .HasColumnType("int");

                    b.Property<int?>("CreatDe")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatLa")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataOra")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EsteSters")
                        .HasColumnType("bit");

                    b.Property<int>("InstitutieId")
                        .HasColumnType("int");

                    b.Property<int?>("ModificatDe")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModificatLa")
                        .HasColumnType("datetime2");

                    b.Property<int>("Optiune")
                        .HasColumnType("int");

                    b.Property<int>("PunctId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int?>("StersDe")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StersLa")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ConsilierId");

                    b.HasIndex("InstitutieId");

                    b.HasIndex("PunctId", "ConsilierId")
                        .IsUnique()
                        .HasFilter("[EsteSters] = 0");

                    b.ToTable("Voturi");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Cleriq.Models.Comisie", b =>
                {
                    b.HasOne("Cleriq.Models.Institutie", "Institutie")
                        .WithMany("Comisii")
                        .HasForeignKey("InstitutieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Institutie");
                });

            modelBuilder.Entity("Cleriq.Models.ComisieMembru", b =>
                {
                    b.HasOne("Cleriq.Models.Comisie", "Comisie")
                        .WithMany("Membri")
                        .HasForeignKey("ComisieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cleriq.Models.Consilier", "Consilier")
                        .WithMany("Apartenente")
                        .HasForeignKey("ConsilierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cleriq.Models.Institutie", "Institutie")
                        .WithMany()
                        .HasForeignKey("InstitutieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Comisie");

                    b.Navigation("Consilier");

                    b.Navigation("Institutie");
                });

            modelBuilder.Entity("Cleriq.Models.ComunicareHclPrefect", b =>
                {
                    b.HasOne("Cleriq.Models.Hcl", "Hcl")
                        .WithMany("Comunicari")
                        .HasForeignKey("HclId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cleriq.Models.Institutie", "Institutie")
                        .WithMany()
                        .HasForeignKey("InstitutieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Hcl");

                    b.Navigation("Institutie");
                });

            modelBuilder.Entity("Cleriq.Models.Consilier", b =>
                {
                    b.HasOne("Cleriq.Models.Institutie", "Institutie")
                        .WithMany("Consilieri")
                        .HasForeignKey("InstitutieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Institutie");
                });

            modelBuilder.Entity("Cleriq.Models.Convocare", b =>
                {
                    b.HasOne("Cleriq.Models.Consilier", "Consilier")
                        .WithMany("Convocari")
                        .HasForeignKey("ConsilierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cleriq.Models.Institutie", "Institutie")
                        .WithMany()
                        .HasForeignKey("InstitutieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cleriq.Models.Sedinta", "Sedinta")
                        .WithMany("Convocari")
                        .HasForeignKey("SedintaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consilier");

                    b.Navigation("Institutie");

                    b.Navigation("Sedinta");
                });

            modelBuilder.Entity("Cleriq.Models.Document", b =>
                {
                    b.HasOne("Cleriq.Models.Hcl", "Hcl")
                        .WithMany("Documente")
                        .HasForeignKey("HclId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Cleriq.Models.Institutie", "Institutie")
                        .WithMany()
                        .HasForeignKey("InstitutieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cleriq.Models.PunctOrdineZi", "Punct")
                        .WithMany("Documente")
                        .HasForeignKey("PunctId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Cleriq.Models.Sedinta", "Sedinta")
                        .WithMany("Documente")
                        .HasForeignKey("SedintaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Hcl");

                    b.Navigation("Institutie");

                    b.Navigation("Punct");

                    b.Navigation("Sedinta");
                });

            modelBuilder.Entity("Cleriq.Models.Hcl", b =>
                {
                    b.HasOne("Cleriq.Models.Institutie", "Institutie")
                        .WithMany()
                        .HasForeignKey("InstitutieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cleriq.Models.PunctOrdineZi", "PunctOrdineZi")
                        .WithMany()
                        .HasForeignKey("PunctOrdineZiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Institutie");

                    b.Navigation("PunctOrdineZi");
                });

            modelBuilder.Entity("Cleriq.Models.IncercareTrimitere", b =>
                {
                    b.HasOne("Cleriq.Models.Convocare", "Convocare")
                        .WithMany("Incercari")
                        .HasForeignKey("ConvocareId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cleriq.Models.Institutie", "Institutie")
                        .WithMany()
                        .HasForeignKey("InstitutieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Convocare");

                    b.Navigation("Institutie");
                });

            modelBuilder.Entity("Cleriq.Models.Mandat", b =>
                {
                    b.HasOne("Cleriq.Models.Consilier", "Consilier")
                        .WithMany("Mandate")
                        .HasForeignKey("ConsilierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cleriq.Models.Institutie", "Institutie")
                        .WithMany()
                        .HasForeignKey("InstitutieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Consilier");

                    b.Navigation("Institutie");
                });

            modelBuilder.Entity("Cleriq.Models.MandatFunctie", b =>
                {
                    b.HasOne("Cleriq.Models.Consilier", "Consilier")
                        .WithMany()
                        .HasForeignKey("ConsilierId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Cleriq.Models.Institutie", "Institutie")
                        .WithMany()
                        .HasForeignKey("InstitutieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cleriq.Models.Persoana", "Persoana")
                        .WithMany("MandateFunctie")
                        .HasForeignKey("PersoanaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Consilier");

                    b.Navigation("Institutie");

                    b.Navigation("Persoana");
                });

            modelBuilder.Entity("Cleriq.Models.Persoana", b =>
                {
                    b.HasOne("Cleriq.Models.Institutie", "Institutie")
                        .WithMany()
                        .HasForeignKey("InstitutieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Institutie");
                });

            modelBuilder.Entity("Cleriq.Models.Prezenta", b =>
                {
                    b.HasOne("Cleriq.Models.Consilier", "Consilier")
                        .WithMany("Prezente")
                        .HasForeignKey("ConsilierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cleriq.Models.Institutie", "Institutie")
                        .WithMany()
                        .HasForeignKey("InstitutieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cleriq.Models.Sedinta", "Sedinta")
                        .WithMany("Prezente")
                        .HasForeignKey("SedintaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consilier");

                    b.Navigation("Institutie");

                    b.Navigation("Sedinta");
                });

            modelBuilder.Entity("Cleriq.Models.ProcesVerbal", b =>
                {
                    b.HasOne("Cleriq.Models.Sedinta", "AprobatInSedinta")
                        .WithMany()
                        .HasForeignKey("AprobatInSedintaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Cleriq.Models.Institutie", "Institutie")
                        .WithMany()
                        .HasForeignKey("InstitutieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cleriq.Models.Sedinta", "Sedinta")
                        .WithOne("ProcesVerbal")
                        .HasForeignKey("Cleriq.Models.ProcesVerbal", "SedintaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AprobatInSedinta");

                    b.Navigation("Institutie");

                    b.Navigation("Sedinta");
                });

            modelBuilder.Entity("Cleriq.Models.PunctOrdineZi", b =>
                {
                    b.HasOne("Cleriq.Models.Institutie", "Institutie")
                        .WithMany()
                        .HasForeignKey("InstitutieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cleriq.Models.Sedinta", "Sedinta")
                        .WithMany("Puncte")
                        .HasForeignKey("SedintaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Institutie");

                    b.Navigation("Sedinta");
                });

            modelBuilder.Entity("Cleriq.Models.RefreshToken", b =>
                {
                    b.HasOne("Cleriq.Models.Utilizator", "Utilizator")
                        .WithMany()
                        .HasForeignKey("UtilizatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilizator");
                });

            modelBuilder.Entity("Cleriq.Models.RelatieHcl", b =>
                {
                    b.HasOne("Cleriq.Models.Hcl", "HclSursa")
                        .WithMany("RelatiiSursa")
                        .HasForeignKey("HclSursaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cleriq.Models.Hcl", "HclTinta")
                        .WithMany("RelatiiTinta")
                        .HasForeignKey("HclTintaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Cleriq.Models.Institutie", "Institutie")
                        .WithMany()
                        .HasForeignKey("InstitutieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HclSursa");

                    b.Navigation("HclTinta");

                    b.Navigation("Institutie");
                });

            modelBuilder.Entity("Cleriq.Models.Sedinta", b =>
                {
                    b.HasOne("Cleriq.Models.Institutie", "Institutie")
                        .WithMany("Sedinte")
                        .HasForeignKey("InstitutieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cleriq.Models.Consilier", "PresedinteSedinta")
                        .WithMany()
                        .HasForeignKey("PresedinteSedintaConsilierId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Institutie");

                    b.Navigation("PresedinteSedinta");
                });

            modelBuilder.Entity("Cleriq.Models.SemnatarHcl", b =>
                {
                    b.HasOne("Cleriq.Models.Consilier", "Consilier")
                        .WithMany()
                        .HasForeignKey("ConsilierId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Cleriq.Models.Hcl", "Hcl")
                        .WithMany("Semnatari")
                        .HasForeignKey("HclId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cleriq.Models.Institutie", "Institutie")
                        .WithMany()
                        .HasForeignKey("InstitutieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cleriq.Models.Persoana", "Persoana")
                        .WithMany()
                        .HasForeignKey("PersoanaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Consilier");

                    b.Navigation("Hcl");

                    b.Navigation("Institutie");

                    b.Navigation("Persoana");
                });

            modelBuilder.Entity("Cleriq.Models.Transcriere", b =>
                {
                    b.HasOne("Cleriq.Models.Institutie", "Institutie")
                        .WithMany()
                        .HasForeignKey("InstitutieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cleriq.Models.Sedinta", "Sedinta")
                        .WithOne("Transcriere")
                        .HasForeignKey("Cleriq.Models.Transcriere", "SedintaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Institutie");

                    b.Navigation("Sedinta");
                });

            modelBuilder.Entity("Cleriq.Models.Utilizator", b =>
                {
                    b.HasOne("Cleriq.Models.Consilier", "Consilier")
                        .WithMany()
                        .HasForeignKey("ConsilierId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Consilier");
                });

            modelBuilder.Entity("Cleriq.Models.Vot", b =>
                {
                    b.HasOne("Cleriq.Models.Consilier", "Consilier")
                        .WithMany("Voturi")
                        .HasForeignKey("ConsilierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cleriq.Models.Institutie", "Institutie")
                        .WithMany()
                        .HasForeignKey("InstitutieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cleriq.Models.PunctOrdineZi", "Punct")
                        .WithMany("Voturi")
                        .HasForeignKey("PunctId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consilier");

                    b.Navigation("Institutie");

                    b.Navigation("Punct");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Cleriq.Models.Rol", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("Cleriq.Models.Utilizator", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("Cleriq.Models.Utilizator", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Cleriq.Models.Rol", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cleriq.Models.Utilizator", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("Cleriq.Models.Utilizator", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Cleriq.Models.Comisie", b =>
                {
                    b.Navigation("Membri");
                });

            modelBuilder.Entity("Cleriq.Models.Consilier", b =>
                {
                    b.Navigation("Apartenente");

                    b.Navigation("Convocari");

                    b.Navigation("Mandate");

                    b.Navigation("Prezente");

                    b.Navigation("Voturi");
                });

            modelBuilder.Entity("Cleriq.Models.Convocare", b =>
                {
                    b.Navigation("Incercari");
                });

            modelBuilder.Entity("Cleriq.Models.Hcl", b =>
                {
                    b.Navigation("Comunicari");

                    b.Navigation("Documente");

                    b.Navigation("RelatiiSursa");

                    b.Navigation("RelatiiTinta");

                    b.Navigation("Semnatari");
                });

            modelBuilder.Entity("Cleriq.Models.Institutie", b =>
                {
                    b.Navigation("Comisii");

                    b.Navigation("Consilieri");

                    b.Navigation("Sedinte");
                });

            modelBuilder.Entity("Cleriq.Models.Persoana", b =>
                {
                    b.Navigation("MandateFunctie");
                });

            modelBuilder.Entity("Cleriq.Models.PunctOrdineZi", b =>
                {
                    b.Navigation("Documente");

                    b.Navigation("Voturi");
                });

            modelBuilder.Entity("Cleriq.Models.Sedinta", b =>
                {
                    b.Navigation("Convocari");

                    b.Navigation("Documente");

                    b.Navigation("Prezente");

                    b.Navigation("ProcesVerbal");

                    b.Navigation("Puncte");

                    b.Navigation("Transcriere");
                });
#pragma warning restore 612, 618
        }
    }
}
