// <auto-generated />
using System;
using Cleriq.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cleriq.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260528072040_AddTipVotPunctOrdineZi")]
    partial class AddTipVotPunctOrdineZi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Cleriq.Models.Comisie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatDe")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatLa")
                        .HasColumnType("datetime2");

                    b.Property<string>("Denumire")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Descriere")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("EsteSters")
                        .HasColumnType("bit");

                    b.Property<int>("InstitutieId")
                        .HasColumnType("int");

                    b.Property<int?>("ModificatDe")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModificatLa")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int?>("StersDe")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StersLa")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("InstitutieId");

                    b.ToTable("Comisii");
                });

            modelBuilder.Entity("Cleriq.Models.ComisieMembru", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ComisieId")
                        .HasColumnType("int");

                    b.Property<int>("ConsilierId")
                        .HasColumnType("int");

                    b.Property<int?>("CreatDe")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatLa")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EsteSters")
                        .HasColumnType("bit");

                    b.Property<int>("InstitutieId")
                        .HasColumnType("int");

                    b.Property<int?>("ModificatDe")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModificatLa")
                        .HasColumnType("datetime2");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int?>("StersDe")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StersLa")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ConsilierId");

                    b.HasIndex("InstitutieId");

                    b.HasIndex("ComisieId", "ConsilierId")
                        .IsUnique()
                        .HasFilter("[EsteSters] = 0");

                    b.ToTable("ComisieMembri");
                });

            modelBuilder.Entity("Cleriq.Models.Consilier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activ")
                        .HasColumnType("bit");

                    b.Property<int?>("CreatDe")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatLa")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EsteSters")
                        .HasColumnType("bit");

                    b.Property<int>("InstitutieId")
                        .HasColumnType("int");

                    b.Property<int?>("ModificatDe")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModificatLa")
                        .HasColumnType("datetime2");

                    b.Property<string>("NumeComplet")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int?>("StersDe")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StersLa")
                        .HasColumnType("datetime2");

                    b.Property<string>("Telefon")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("InstitutieId");

                    b.ToTable("Consilieri");
                });

            modelBuilder.Entity("Cleriq.Models.Convocare", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ConsilierId")
                        .HasColumnType("int");

                    b.Property<int?>("CreatDe")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatLa")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailDetalii")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("EmailStatus")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EmailTrimisLa")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EsteSters")
                        .HasColumnType("bit");

                    b.Property<int>("InstitutieId")
                        .HasColumnType("int");

                    b.Property<int?>("ModificatDe")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModificatLa")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("SedintaId")
                        .HasColumnType("int");

                    b.Property<string>("SmsDetalii")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("SmsStatus")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SmsTrimisLa")
                        .HasColumnType("datetime2");

                    b.Property<int?>("StersDe")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StersLa")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ConsilierId");

                    b.HasIndex("InstitutieId");

                    b.HasIndex("SedintaId", "ConsilierId")
                        .IsUnique()
                        .HasFilter("[EsteSters] = 0");

                    b.ToTable("Convocari");
                });

            modelBuilder.Entity("Cleriq.Models.Institutie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodSiruta")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("CreatDe")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatLa")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataExpirare")
                        .HasColumnType("datetime2");

                    b.Property<string>("Denumire")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("EsteSters")
                        .HasColumnType("bit");

                    b.Property<string>("FusOrar")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("Europe/Bucharest");

                    b.Property<string>("Judet")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ModificatDe")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModificatLa")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("StatusAbonament")
                        .HasColumnType("int");

                    b.Property<int?>("StersDe")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StersLa")
                        .HasColumnType("datetime2");

                    b.Property<int>("Tip")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Institutii");
                });

            modelBuilder.Entity("Cleriq.Models.Mandat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ConsilierId")
                        .HasColumnType("int");

                    b.Property<int?>("CreatDe")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatLa")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("DataInceput")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DataSfarsit")
                        .HasColumnType("date");

                    b.Property<bool>("EsteSters")
                        .HasColumnType("bit");

                    b.Property<string>("GrupPolitic")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("InstitutieId")
                        .HasColumnType("int");

                    b.Property<int?>("ModificatDe")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModificatLa")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int?>("StersDe")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StersLa")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ConsilierId");

                    b.HasIndex("InstitutieId");

                    b.ToTable("Mandate");
                });

            modelBuilder.Entity("Cleriq.Models.Prezenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ConsilierId")
                        .HasColumnType("int");

                    b.Property<int?>("CreatDe")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatLa")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EsteSters")
                        .HasColumnType("bit");

                    b.Property<int>("InstitutieId")
                        .HasColumnType("int");

                    b.Property<int?>("ModificatDe")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModificatLa")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("OraSosire")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("SedintaId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("StersDe")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StersLa")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ConsilierId");

                    b.HasIndex("InstitutieId");

                    b.HasIndex("SedintaId", "ConsilierId")
                        .IsUnique()
                        .HasFilter("[EsteSters] = 0");

                    b.ToTable("Prezente");
                });

            modelBuilder.Entity("Cleriq.Models.ProcesVerbal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Continut")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreatDe")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatLa")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataFinalizare")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataGenerare")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EsteSters")
                        .HasColumnType("bit");

                    b.Property<int>("InstitutieId")
                        .HasColumnType("int");

                    b.Property<int?>("ModificatDe")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModificatLa")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("SedintaId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("StersDe")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StersLa")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("InstitutieId");

                    b.HasIndex("SedintaId")
                        .IsUnique();

                    b.ToTable("ProceseVerbale");
                });

            modelBuilder.Entity("Cleriq.Models.PunctOrdineZi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatDe")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatLa")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descriere")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EsteSters")
                        .HasColumnType("bit");

                    b.Property<int>("InstitutieId")
                        .HasColumnType("int");

                    b.Property<int?>("ModificatDe")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModificatLa")
                        .HasColumnType("datetime2");

                    b.Property<bool>("NecesitaVot")
                        .HasColumnType("bit");

                    b.Property<int>("Ordine")
                        .HasColumnType("int");

                    b.Property<int?>("Rezultat")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("SedintaId")
                        .HasColumnType("int");

                    b.Property<int?>("StersDe")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StersLa")
                        .HasColumnType("datetime2");

                    b.Property<int>("Tip")
                        .HasColumnType("int");

                    b.Property<int?>("TipMajoritate")
                        .HasColumnType("int");

                    b.Property<int>("TipVot")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("Titlu")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("InstitutieId");

                    b.HasIndex("SedintaId");

                    b.ToTable("PuncteOrdineZi");
                });

            modelBuilder.Entity("Cleriq.Models.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Cleriq.Models.Sedinta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ConvocareTrimisaLa")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatDe")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatLa")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataOra")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EsteSters")
                        .HasColumnType("bit");

                    b.Property<int>("InstitutieId")
                        .HasColumnType("int");

                    b.Property<string>("Loc")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("ModDesfasurare")
                        .HasColumnType("int");

                    b.Property<int?>("ModificatDe")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModificatLa")
                        .HasColumnType("datetime2");

                    b.Property<string>("Numar")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("StersDe")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StersLa")
                        .HasColumnType("datetime2");

                    b.Property<int>("Tip")
                        .HasColumnType("int");

                    b.Property<string>("Titlu")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("InstitutieId");

                    b.ToTable("Sedinte");
                });

            modelBuilder.Entity("Cleriq.Models.Utilizator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("InstitutieId")
                        .HasColumnType("int");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NumeComplet")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Cleriq.Models.Vot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ConsilierId")
                        .HasColumnType("int");

                    b.Property<int?>("CreatDe")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatLa")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataOra")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EsteSters")
                        .HasColumnType("bit");

                    b.Property<int>("InstitutieId")
                        .HasColumnType("int");

                    b.Property<int?>("ModificatDe")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModificatLa")
                        .HasColumnType("datetime2");

                    b.Property<int>("Optiune")
                        .HasColumnType("int");

                    b.Property<int>("PunctId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int?>("StersDe")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StersLa")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ConsilierId");

                    b.HasIndex("InstitutieId");

                    b.HasIndex("PunctId", "ConsilierId")
                        .IsUnique()
                        .HasFilter("[EsteSters] = 0");

                    b.ToTable("Voturi");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Cleriq.Models.Comisie", b =>
                {
                    b.HasOne("Cleriq.Models.Institutie", "Institutie")
                        .WithMany("Comisii")
                        .HasForeignKey("InstitutieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Institutie");
                });

            modelBuilder.Entity("Cleriq.Models.ComisieMembru", b =>
                {
                    b.HasOne("Cleriq.Models.Comisie", "Comisie")
                        .WithMany("Membri")
                        .HasForeignKey("ComisieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cleriq.Models.Consilier", "Consilier")
                        .WithMany("Apartenente")
                        .HasForeignKey("ConsilierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cleriq.Models.Institutie", "Institutie")
                        .WithMany()
                        .HasForeignKey("InstitutieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Comisie");

                    b.Navigation("Consilier");

                    b.Navigation("Institutie");
                });

            modelBuilder.Entity("Cleriq.Models.Consilier", b =>
                {
                    b.HasOne("Cleriq.Models.Institutie", "Institutie")
                        .WithMany("Consilieri")
                        .HasForeignKey("InstitutieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Institutie");
                });

            modelBuilder.Entity("Cleriq.Models.Convocare", b =>
                {
                    b.HasOne("Cleriq.Models.Consilier", "Consilier")
                        .WithMany("Convocari")
                        .HasForeignKey("ConsilierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cleriq.Models.Institutie", "Institutie")
                        .WithMany()
                        .HasForeignKey("InstitutieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cleriq.Models.Sedinta", "Sedinta")
                        .WithMany("Convocari")
                        .HasForeignKey("SedintaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consilier");

                    b.Navigation("Institutie");

                    b.Navigation("Sedinta");
                });

            modelBuilder.Entity("Cleriq.Models.Mandat", b =>
                {
                    b.HasOne("Cleriq.Models.Consilier", "Consilier")
                        .WithMany("Mandate")
                        .HasForeignKey("ConsilierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cleriq.Models.Institutie", "Institutie")
                        .WithMany()
                        .HasForeignKey("InstitutieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Consilier");

                    b.Navigation("Institutie");
                });

            modelBuilder.Entity("Cleriq.Models.Prezenta", b =>
                {
                    b.HasOne("Cleriq.Models.Consilier", "Consilier")
                        .WithMany("Prezente")
                        .HasForeignKey("ConsilierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cleriq.Models.Institutie", "Institutie")
                        .WithMany()
                        .HasForeignKey("InstitutieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cleriq.Models.Sedinta", "Sedinta")
                        .WithMany("Prezente")
                        .HasForeignKey("SedintaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consilier");

                    b.Navigation("Institutie");

                    b.Navigation("Sedinta");
                });

            modelBuilder.Entity("Cleriq.Models.ProcesVerbal", b =>
                {
                    b.HasOne("Cleriq.Models.Institutie", "Institutie")
                        .WithMany()
                        .HasForeignKey("InstitutieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cleriq.Models.Sedinta", "Sedinta")
                        .WithOne("ProcesVerbal")
                        .HasForeignKey("Cleriq.Models.ProcesVerbal", "SedintaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Institutie");

                    b.Navigation("Sedinta");
                });

            modelBuilder.Entity("Cleriq.Models.PunctOrdineZi", b =>
                {
                    b.HasOne("Cleriq.Models.Institutie", "Institutie")
                        .WithMany()
                        .HasForeignKey("InstitutieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cleriq.Models.Sedinta", "Sedinta")
                        .WithMany("Puncte")
                        .HasForeignKey("SedintaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Institutie");

                    b.Navigation("Sedinta");
                });

            modelBuilder.Entity("Cleriq.Models.Sedinta", b =>
                {
                    b.HasOne("Cleriq.Models.Institutie", "Institutie")
                        .WithMany("Sedinte")
                        .HasForeignKey("InstitutieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Institutie");
                });

            modelBuilder.Entity("Cleriq.Models.Vot", b =>
                {
                    b.HasOne("Cleriq.Models.Consilier", "Consilier")
                        .WithMany("Voturi")
                        .HasForeignKey("ConsilierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cleriq.Models.Institutie", "Institutie")
                        .WithMany()
                        .HasForeignKey("InstitutieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Cleriq.Models.PunctOrdineZi", "Punct")
                        .WithMany("Voturi")
                        .HasForeignKey("PunctId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consilier");

                    b.Navigation("Institutie");

                    b.Navigation("Punct");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Cleriq.Models.Rol", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("Cleriq.Models.Utilizator", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("Cleriq.Models.Utilizator", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Cleriq.Models.Rol", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cleriq.Models.Utilizator", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("Cleriq.Models.Utilizator", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Cleriq.Models.Comisie", b =>
                {
                    b.Navigation("Membri");
                });

            modelBuilder.Entity("Cleriq.Models.Consilier", b =>
                {
                    b.Navigation("Apartenente");

                    b.Navigation("Convocari");

                    b.Navigation("Mandate");

                    b.Navigation("Prezente");

                    b.Navigation("Voturi");
                });

            modelBuilder.Entity("Cleriq.Models.Institutie", b =>
                {
                    b.Navigation("Comisii");

                    b.Navigation("Consilieri");

                    b.Navigation("Sedinte");
                });

            modelBuilder.Entity("Cleriq.Models.PunctOrdineZi", b =>
                {
                    b.Navigation("Voturi");
                });

            modelBuilder.Entity("Cleriq.Models.Sedinta", b =>
                {
                    b.Navigation("Convocari");

                    b.Navigation("Prezente");

                    b.Navigation("ProcesVerbal");

                    b.Navigation("Puncte");
                });
#pragma warning restore 612, 618
        }
    }
}
