// <auto-generated />
using System;
using Cleriq.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cleriq.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260518081943_AddMandat")]
    partial class AddMandat
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Cleriq.Models.Comisie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Denumire")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Descriere")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("InstitutieId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InstitutieId");

                    b.ToTable("Comisii");
                });

            modelBuilder.Entity("Cleriq.Models.ComisieMembru", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ComisieId")
                        .HasColumnType("int");

                    b.Property<int>("ConsilierId")
                        .HasColumnType("int");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ComisieId");

                    b.HasIndex("ConsilierId");

                    b.ToTable("ComisieMembri");
                });

            modelBuilder.Entity("Cleriq.Models.Consilier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activ")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("InstitutieId")
                        .HasColumnType("int");

                    b.Property<string>("NumeComplet")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Telefon")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("InstitutieId");

                    b.ToTable("Consilieri");
                });

            modelBuilder.Entity("Cleriq.Models.Institutie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodSiruta")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("DataExpirare")
                        .HasColumnType("datetime2");

                    b.Property<string>("Denumire")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Judet")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("StatusAbonament")
                        .HasColumnType("int");

                    b.Property<int>("Tip")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Institutii");
                });

            modelBuilder.Entity("Cleriq.Models.Mandat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ConsilierId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("DataInceput")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DataSfarsit")
                        .HasColumnType("date");

                    b.Property<string>("GrupPolitic")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ConsilierId");

                    b.ToTable("Mandate");
                });

            modelBuilder.Entity("Cleriq.Models.Comisie", b =>
                {
                    b.HasOne("Cleriq.Models.Institutie", "Institutie")
                        .WithMany("Comisii")
                        .HasForeignKey("InstitutieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Institutie");
                });

            modelBuilder.Entity("Cleriq.Models.ComisieMembru", b =>
                {
                    b.HasOne("Cleriq.Models.Comisie", "Comisie")
                        .WithMany("Membri")
                        .HasForeignKey("ComisieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cleriq.Models.Consilier", "Consilier")
                        .WithMany("Apartenente")
                        .HasForeignKey("ConsilierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Comisie");

                    b.Navigation("Consilier");
                });

            modelBuilder.Entity("Cleriq.Models.Consilier", b =>
                {
                    b.HasOne("Cleriq.Models.Institutie", "Institutie")
                        .WithMany("Consilieri")
                        .HasForeignKey("InstitutieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Institutie");
                });

            modelBuilder.Entity("Cleriq.Models.Mandat", b =>
                {
                    b.HasOne("Cleriq.Models.Consilier", "Consilier")
                        .WithMany("Mandate")
                        .HasForeignKey("ConsilierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consilier");
                });

            modelBuilder.Entity("Cleriq.Models.Comisie", b =>
                {
                    b.Navigation("Membri");
                });

            modelBuilder.Entity("Cleriq.Models.Consilier", b =>
                {
                    b.Navigation("Apartenente");

                    b.Navigation("Mandate");
                });

            modelBuilder.Entity("Cleriq.Models.Institutie", b =>
                {
                    b.Navigation("Comisii");

                    b.Navigation("Consilieri");
                });
#pragma warning restore 612, 618
        }
    }
}
